[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_PROJECT_ID,VITE_SUPABASE_PUBLISHABLE_KEY"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for 1 year (immutable files)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images for 1 week
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Cache uploaded images for 1 week
[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Cache fonts for 1 year
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS for 1 year (with versioning)
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for 1 hour (allow updates)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Product detail page redirect
[[redirects]]
  from = "/product/:id"
  to = "/index.html"
  status = 200

# Contact page redirect
[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

# Privacy page redirect
[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200