[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/index.html"
  [headers.values]
  Cache-Control = "no-cache"

# Next.js-style static assets
[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Image caching (adjust to your path)
[[headers]]
for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=604800"

[[redirects]]
from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"